# Generated by Django 5.2.6 on 2025-11-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Tarjeta de Crédito'), ('debito', 'Tarjeta de Débito'), ('qr', 'QR')], default='efectivo', max_length=20),
        ),
    ]
