# Generated by Django 5.2.6 on 2025-10-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='TEMP-SKU', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
