# Generated by Django 5.2.6 on 2025-10-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='TEMP-SKU', max_length=20, unique=True),
        ),
    ]
