# Generated by Django 5.2.6 on 2025-10-13 21:47

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: jpg, png, gif. Tamaño máximo: 5MB', null=True, upload_to=productos.models.get_image_path, validators=[productos.models.validate_image_size], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(help_text='Debe coincidir con el nombre del archivo de imagen (sin extensión)', max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, verbose_name='Stock Mínimo'),
        ),
    ]
